set -g default-terminal "tmux-256color"
set -g base-index 1
set -g mouse on
set -g status-right ''

# Meaningful pane split commands
bind | split-window -h
bind _ split-window -v
# Unbinding old split keys
unbind '"'
unbind '%'

# don't rename windows automatically
set-option -g allow-rename off

# vi mode
set-window-option -g mode-keys vi

# style
setw -g window-status-current-style 'fg=black bg=red'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=red bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '
