[colors]
background = '#111318'
foreground = '#e1e2e9'

cursor_bg = '#a4c9fe'
cursor_fg = '#111318'
cursor_border = '#a4c9fe'

selection_bg = '#204876'
selection_fg = '#e1e2e9'

ansi = ['#111318', '#ff729b', '#7ffe90', '#fff772', '#8ab4f1', '#294875', '#a4c9fe', '#eff5ff']
brights = ['#989da5', '#ff9fbb', '#a5ffb2', '#fffaa5', '#b2d1ff', '#bfd9ff', '#d6e7ff', '#f8fbff']
