[shell]
niri_overview_type_to_launch_enabled = true

[bar.main]
position = "right"
thickness = 30
margin_ends = 4
margin_opposite_edge = 4
margin_edge = 4
concave_edge_corners = false

start = ["launcher", "workspaces", "taskbar"]
center = []
end = [
  "clock",
  "notifications",
  "network",
  "bluetooth",
  "volume",
  "temp",
  "battery",
  "session",
]
